# Generated by Django 5.0 on 2024-02-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_4_laba', '0004_cat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
