# Generated by Django 5.0 on 2024-02-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_4_laba', '0005_alter_cat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='like',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
