# Generated by Django 5.0 on 2024-02-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_4_laba', '0006_cat_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='title',
        ),
    ]
